In [38]:
import numpy as np

In [39]:
myarr = np.array([3,6,32,7])

In [40]:
myarr

array([ 3,  6, 32,  7])

In [41]:
myarr1 = np.array([3,6,37,7] , np.int32)


In [42]:
myarr1

array([ 3,  6, 37,  7])

In [43]:
myarr1.dtype

dtype('int32')

In [44]:
# Array Creation : Conversion from other python structures.

In [45]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [46]:

listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [47]:
listarray.dtype

dtype('int32')

In [48]:
listarray.shape

(3, 3)

In [49]:
listarray.size

9

In [50]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [51]:
zeros = np.zeros((2,5))

In [52]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
zeros.dtype

dtype('float64')

In [54]:
zeros.shape

(2, 5)

In [55]:
zeros.size

10

In [56]:
rng = np.arange(15)

In [57]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
lspace = np.linspace(1,5,12)

In [59]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [60]:
lspace1 = np.linspace(1,4,4)

In [61]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [62]:
emp = np.empty((4,6))

In [63]:
emp_like = np.empty_like(lspace)

In [64]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [65]:
ide = np.identity(45)

In [66]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [67]:
ide.shape

(45, 45)

In [68]:
arr = np.arange(99)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [70]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [71]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [72]:
x = [[1,2,3], [4,5,6],[7,1,0]]

In [73]:
arr = np.array(x)

In [74]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
arr.sum(axis=0)

array([12,  8,  9])

In [76]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [77]:
arr.flat

In [79]:
for item in arr.flat :
    print(item)

1
2
3
4
5
6
7
1
0


In [80]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [81]:
arr.ndim

2

In [82]:
arr.size

9

In [83]:
arr.nbytes

36

In [86]:
one = np.array([1,3,61,86])

In [87]:
one.argmax()

3

In [88]:
one.argmin()

0

In [89]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [90]:
arr.argmax()

6

In [91]:
arr.argmin()

8

In [92]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [93]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [94]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [95]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [96]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [98]:
arr2 = np.array([[1,8,3],[2,3,4],[0,1,7]])

In [99]:
arr+arr2

array([[ 2, 10,  6],
       [ 6,  8, 10],
       [ 7,  2,  7]])

In [100]:
arr*arr2

array([[ 1, 16,  9],
       [ 8, 15, 24],
       [ 0,  1,  0]])

In [101]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [102]:
arr.sum()

29

In [103]:
arr.max()

7

In [104]:
arr.min()

0

In [105]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [106]:
np.count_nonzero(arr)

8

In [107]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [3]:
import sys

In [1]:
py_ar = [0,4,55,5]

In [4]:
sys.getsizeof(1)

28

In [8]:
sys.getsizeof(1)*len(py_ar)

112